force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>SEN-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/X__c.field-meta.xml
<CustomField>
    <fullName>X__c</fullName>
    <label>X</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Y__c.field-meta.xml
<CustomField>
    <fullName>Y__c</fullName>
    <label>Y</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Z__c.field-meta.xml
<CustomField>
    <fullName>Z__c</fullName>
    <label>Z</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorControllerTest.cls
@isTest
public class SensorControllerTest {
    
    @isTest
    static void testGetSensors() {
        
        Sensor__c sensor1 = new Sensor__c(Name = 'Sensor 1');
        Sensor__c sensor2 = new Sensor__c(Name = 'Sensor 2');
        insert new List<Sensor__c> { sensor1, sensor2 };
        
        Test.startTest();
        List<Sensor__c> result = SensorController.getSensors();
        Test.stopTest();
        
       
        
        System.assertEquals(2, result.size(), 'Очікувалося 2 сенсори');
    }
    
    @isTest
    static void testGetSensorEvents() {
        
        Sensor__c sensor = new Sensor__c(Name = 'Sensor 1');
        insert sensor;
        
        Sensor_Event__c event1 = new Sensor_Event__c(Sensor__c = sensor.Id, x__c = 1, y__c = 1, z__c = 1);
        Sensor_Event__c event2 = new Sensor_Event__c(Sensor__c = sensor.Id, x__c = 2, y__c = 2, z__c = 2);
        insert new List<Sensor_Event__c> { event1, event2 };
        
        
        Test.startTest();
        List<Sensor_Event__c> result = SensorController.getSensorEvents(sensor.Id);
        Test.stopTest();
        
        
        
        System.assertEquals(2, result.size(), 'Очікувалося 2 події сенсора');
    }
}